{"name": "用例标题 = 传失效的token", "status": "passed", "attachments": [{"name": "log", "source": "533538d4-26c3-4f52-a3e1-c60116627fad-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'detail': '传失效的token', 'data': {'cgs_token': 'fbf66c79988e43608bccc68088d7d123', 'pageIndex': '1'}, 'resp': {'code': '204', 'message': '用户Token失效，请重新登录.'}}"}, {"name": "url_method", "value": "{'url': '/cgsfront/appointment/getHandlingRecord', 'method': 'post'}"}], "start": 1657093626344, "stop": 1657093626409, "uuid": "8558b396-1894-486a-96aa-b95e3f23b9b9", "historyId": "c7e5c3f6b696e690059a53ad8501ad69", "testCaseId": "d92941eb36fefbf4ef56b53b6429753a", "fullName": "test_case.test_req#test_select", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_req"}, {"name": "host", "value": "DESKTOP-9BAFSPC"}, {"name": "thread", "value": "17240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_req"}]}